# Generated by Django 3.1.7 on 2021-06-25 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('basetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('stopwatch', models.CharField(max_length=20)),
            ],
        ),
    ]
