# Generated by Django 3.1.7 on 2021-06-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_counter_iid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='stopwatch',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
    ]
